In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, date
from sweref99 import projections

In [2]:
path='./data/Brandriskdata 2000-2020.csv'
#'PunktID': str, 'E': str, 'N': str,
types={ 'PunktID': str}

In [3]:
#Reading csv file from path with dtypes
df = pd.read_csv(path, sep=';', dtype=types, )

In [67]:
#tm is used for the conversions of easting and northing to longitude and latitude
tm = projections.make_transverse_mercator("SWEREF_99_TM")

In [130]:
#For now sample is only 50 values
sample = df.sample(50)
sample[['E','N']] = df[['E','N']].fillna(0)
sample['N'] = sample['N'].astype(int)
sample['E'] = sample['E'].astype(int)
sample.head(10)

,PunktID,E,N,Kommun,Datum,Temp,Tmedel,Nederbord,RH,Vindhastighet,...,DC,ISI,BUI,FWI,FWI_index,HBV_o,HBV_u,HBV,HBV_index,Gras
12018829,4933,602338,6883520,2132.0,2000-07-11,"14,9","13,6","4,4",81,"4,1",...,"204,3","1,5","19,7",2,2.0,75.0,50.0,77.0,1.0,NaN
11072450,4527,445616,6789520,2039.0,2018-09-10,"12,2",12,10,"95,8","3,035354",...,"346,2",0,"8,5",0,1.0,88.0,42.0,90.0,1.0,-1.0
12007747,4926,615475,7309578,2506.0,2017-06-16,"18,3",13,"1,3","45,5","0,14997",...,"123,6","1,3","41,8","3,2",2.0,43.0,70.0,71.0,2.0,2.0
10011077,4108,700821,7012535,2284.0,2012-05-03,"10,5",6,0,"30,3","5,7",...,"35,7","10,2","11,9","11,2",3.0,63.0,70.0,67.0,2.0,4.0
3343812,1391,624412,7030514,2284.0,2020-07-09,"13,4",11,"10,6","67,9",2,...,"112,4",0,"4,2",0,1.0,87.0,61.0,91.0,1.0,-1.0
1692708,703,402240,6770692,2023.0,2011-08-25,"13,3",12,"3,7","94,5","2,1",...,"140,7","0,1","5,2",0,1.0,79.0,67.0,84.0,1.0,NaN
7200190,2942,467204,6601452,1760.0,2004-08-16,"18,1","15,2","1,7",74,"1,8",...,"322,2",1,"53,5","2,8",2.0,51.0,41.0,56.0,3.0,NaN
2904387,1202,687426,7281274,2505.0,2018-07-03,"22,4",16,0,"38,4","2,104587",...,"226,1","7,5","44,3","16,9",3.0,51.0,42.0,47.0,3.0,-1.0
10263324,4199,400076,6795501,2023.0,2014-05-14,6,3,"0,8","35,7","3,1",...,0,0,0,0,1.0,95.0,96.0,100.0,1.0,1.0
5571714,2321,601192,7483079,2510.0,2005-04-20,"-1,7","-6,2",0,73,"6,8",...,0,0,0,0,1.0,100.0,94.0,100.0,1.0,NaN

In [121]:
#Function that calculates number of missing data in column of dataframe and prints result.
def missing(df,column):
       x = len(df)
       if df[column].isnull().any():
           print('{0} has total of {1} null values'.format(column, df[column].isnull().sum()))
           print ('In the column {0}'.format(column), round(df[column].count()-1/x * 100, 3), '% of the cells have missing values')

In [129]:
#Missing values of column 'Gras'
missing(sample,'Gras')
missing(sample,'Vindriktning')
sample.isnull().sum(axis = 0)

Gras has total of 15 null values
In the column Gras 33.0 % of the cells have missing values
Vindriktning has total of 31 null values
In the column Vindriktning 17.0 % of the cells have missing values

PunktID           0
E                 0
N                 0
Kommun            0
Datum             0
Temp              0
Tmedel            1
Nederbord         0
RH                1
Vindhastighet     0
Vindriktning     31
FFMC              1
DMC               1
DC                1
ISI               1
BUI               1
FWI               1
FWI_index         1
HBV_o             1
HBV_u             1
HBV               1
HBV_index         1
Gras             15
Latitude          0
Longitude         0
dtype: int64

In [100]:
#Data info
sample.describe()

,E,N,Kommun,FWI_index,HBV_o,HBV_u,HBV,HBV_index,Gras
count,50.000000,5.000000e+01,50.000000,49.000000,49.000000,49.000000,49.000000,49.000000,35.000000
mean,613332.420000,7.005175e+06,1974.440000,1.285714,74.061224,64.489796,78.265306,1.551020,1.485714
std,140132.354559,3.980938e+05,784.369112,1.322876,23.512770,21.906166,21.174646,0.818057,1.462702
min,355450.000000,6.129645e+06,125.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,-1.000000
25%,517557.000000,6.679040e+06,1748.500000,1.000000,62.000000,53.000000,66.000000,1.000000,1.000000
50%,609857.000000,7.094570e+06,2363.500000,1.000000,78.000000,69.000000,82.000000,1.000000,1.000000
75%,720308.250000,7.301608e+06,2510.000000,2.000000,93.000000,81.000000,100.000000,2.000000,2.000000
max,894469.000000,7.670400e+06,2584.000000,5.000000,100.000000,100.000000,100.000000,4.000000,5.000000

In [123]:
#Functions for converting easting and northing to latitudes and longitudes.
def toLat(E,N):
    lat, lon = tm.grid_to_geodetic(N,E)
    return lat
def toLon(E,N):
    lat, lon = tm.grid_to_geodetic(N,E)
    return lon

In [124]:
#Applying functions to create to new columns, Longitude and Latitude for reported fires.
sample['Latitude'] = sample.apply(lambda row: toLat(row['E'],row['N']),axis=1)
sample['Longitude'] = sample.apply(lambda row: toLon(row['E'],row['N']),axis=1)
sample

,PunktID,E,N,Kommun,Datum,Temp,Tmedel,Nederbord,RH,Vindhastighet,...,BUI,FWI,FWI_index,HBV_o,HBV_u,HBV,HBV_index,Gras,Latitude,Longitude
13746976,5651,534500,6802426,2121.0,2020-04-12,"10,9",6,"0,9","51,6","6,5",...,"12,7","6,9",2.0,61.0,77.0,81.0,1.0,3.0,61.354333,15.645080
13573718,5590,589502,6577364,484.0,2017-09-20,"11,7",8,"0,9","62,3","1,765884",...,"17,8","0,9",1.0,78.0,35.0,77.0,1.0,2.0,59.325588,16.572816
9922545,4077,653237,7043151,2284.0,2004-09-25,"9,9","8,5",0,61,"3,4",...,3,"0,4",1.0,87.0,75.0,83.0,1.0,NaN,63.483558,18.077141
3289658,1377,747792,7101939,2480.0,2018-02-09,"0,2",-2,"0,9","96,5","5,534387",...,0,0,-1.0,100.0,95.0,100.0,1.0,1.0,63.955858,20.062132
6591247,2700,787288,7565699,2584.0,2013-03-02,"-12,8",-19,"0,9","76,2","3,7",...,0,0,1.0,98.0,84.0,100.0,1.0,1.0,68.060621,21.902207
14005215,5752,717890,7449061,2523.0,2002-08-16,"20,9","14,2",0,47,"3,4",...,"30,9","6,5",2.0,63.0,46.0,56.0,3.0,NaN,67.079704,20.018089
4734652,1974,649549,6577753,125.0,2013-06-14,"19,2",16,"5,4","66,8","4,7",...,"22,4","0,6",1.0,71.0,36.0,70.0,2.0,2.0,59.312084,17.627261
18663857,7685,650662,7187888,2481.0,2006-04-21,"4,9","0,8",0,36,"4,3",...,0,0,1.0,100.0,89.0,100.0,1.0,NaN,64.781611,18.170106
7278414,2985,439281,6409002,643.0,2008-07-19,"19,2","15,6","1,2",57,"3,3",...,"29,2","2,2",2.0,62.0,46.0,66.0,2.0,NaN,57.818860,13.977899
15162967,6222,670835,7539501,2584.0,2016-03-16,"0,8",2,"0,4","74,8","6,816781",...,0,0,1.0,98.0,81.0,100.0,1.0,1.0,67.919316,19.074781
7955296,3262,564257,7449741,2506.0,2019-06-11,"5,9",3,"0,8","86,7","2,5",...,0,0,-1.0,99.0,100.0,100.0,1.0,1.0,67.157827,16.483440
2217644,926,663640,6644036,380.0,2016-07-20,"24,6",18,0,"36,3","0,835755",...,43,"12,8",3.0,48.0,35.0,42.0,4.0,2.0,59.901308,17.925714
1034150,442,869563,7413847,2518.0,2005-06-30,"18,7","13,7",0,41,3,...,"20,3","3,5",2.0,69.0,53.0,63.0,2.0,NaN,66.620031,23.366087
955640,408,471947,6491890,1446.0,2020-12-15,"6,9",6,"6,3","92,4","4,2",...,"0,1",0,-1.0,98.0,76.0,100.0,1.0,-1.0,58.566555,14.517761
15129201,6207,700532,7072519,2401.0,2015-05-12,12,9,7,"67,5","2,3",...,"7,3","0,1",1.0,78.0,78.0,88.0,1.0,3.0,63.722946,19.061760
8432432,3468,734288,7670400,2584.0,2010-06-26,"16,7","13,4","2,2",57,"3,5",...,"9,8","0,7",1.0,74.0,70.0,82.0,1.0,2.0,69.043084,20.877210
18911770,7795,420055,7087202,2309.0,2020-05-03,"1,7",0,"3,9","91,1","8,3",...,0,0,-1.0,100.0,98.0,100.0,1.0,1.0,63.902785,13.371062
15556255,6387,527120,7296556,2421.0,2020-07-04,"12,1",8,"0,7","43,9","4,9",...,0,0,-1.0,51.0,59.0,100.0,1.0,-1.0,65.789326,15.592656
17428285,7162,597078,7472714,2510.0,2019-01-11,"-4,4",-5,"18,7","97,3","19,5",...,0,0,-1.0,100.0,92.0,100.0,1.0,1.0,67.354923,17.259830
6041592,2492,612689,6879457,2132.0,2012-05-09,"6,5",4,"4,5","93,3",3,...,"6,5",0,1.0,83.0,72.0,89.0,1.0,3.0,62.030572,17.153928
9716282,3998,519417,6521110,583.0,2004-08-17,19,"16,4","6,5",82,"2,1",...,"27,7","0,2",1.0,66.0,44.0,68.0,2.0,NaN,58.829448,15.336307
1817543,754,459466,6975713,2326.0,2016-02-14,"-9,2",-11,"1,2","80,1","1,437754",...,0,0,1.0,99.0,85.0,100.0,1.0,1.0,62.909103,14.202228
8840874,3642,523650,6926436,2260.0,2004-05-03,"17,1",12,"2,5",60,"5,3",...,"31,4","4,4",2.0,54.0,61.0,67.0,2.0,NaN,62.468310,15.458589
14168732,5829,591119,7547055,2523.0,2007-06-11,"4,2","5,1","11,9",89,"1,7",...,0,0,1.0,93.0,97.0,100.0,1.0,1.0,68.023153,17.182190
2341274,978,607025,6773942,2182.0,2005-07-02,"21,2","15,2",0,45,"2,3",...,"34,5","9,8",3.0,50.0,47.0,48.0,3.0,NaN,61.085578,16.984350
16035213,6607,564277,7150010,2425.0,2003-04-04,"2,5","-1,5","4,2",60,"6,7",...,0,0,1.0,98.0,82.0,100.0,1.0,NaN,64.469499,16.336679
2125898,880,389947,6739609,1737.0,2008-05-16,"2,7","3,2","11,7",91,"2,5",...,"13,9",0,1.0,82.0,76.0,90.0,1.0,5.0,60.776694,12.979166
6161743,2539,741539,7116357,2480.0,2007-05-08,"12,5","7,1","0,2",70,3,...,"55,1","10,4",3.0,30.0,71.0,59.0,2.0,3.0,64.089156,19.957837
9018271,3720,389166,6129645,1287.0,2018-03-08,"0,8",1,"3,9","94,9","4,807479",...,0,0,-1.0,93.0,84.0,100.0,1.0,1.0,55.300724,13.254191
1006846,422,404407,6350912,662.0,2014-08-03,25,21,7,"67,8","3,2",...,"35,3","1,7",2.0,65.0,39.0,66.0,2.0,0.0,57.291172,13.413906
16040753,6608,645470,6567385,140.0,2006-08-30,"21,5","15,6",0,41,"2,4",...,"14,7","4,4",2.0,81.0,57.0,73.0,2.0,NaN,59.220494,17.548724
16191810,6669,516937,7120767,2313.0,2011-08-02,"21,3",18,"1,5","73,5","1,8",...,"26,4","1,5",2.0,56.0,38.0,58.0,3.0,NaN,64.212739,15.348930
1680946,696,638460,6701773,360.0,2000-07-30,"20,4","15,3","0,4",52,"0,8",...,"13,9","3,3",2.0,72.0,65.0,69.0,2.0,NaN,60.428457,17.515359
9977983,4093,473821,6527050,1860.0,2015-09-25,"13,8",12,"0,3","63,8","4,7",...,"2,7","0,3",1.0,86.0,73.0,92.0,1.0,2.0,58.882435,14.545880
4620886,1936,578308,6366393,882.0,2015-05-19,"8,2",8,"13,4","96,4","2,3",...,"13,6",0,1.0,82.0,53.0,84.0,1.0,2.0,57.433491,16.304315
1615716,665,790065,7301020,2582.0,2014-05-28,"14,2",10,0,"41,5",3,...,"29,2","9,2",3.0,63.0,56.0,60.0,2.0,2.0,65.699424,21.325238
16445205,6781,514940,7085606,2313.0,2004-09-30,"8,3","4,4",0,67,1,...,3,"0,2",1.0,92.0,68.0,88.0,1.0,NaN,63.897302,15.304330
2906129,1205,720421,7244383,2482.0,2004-07-07,10,"11,3","7,9",84,"3,8",...,"0,8",0,1.0,88.0,75.0,93.0,1.0,NaN,65.248313,19.721543
12388934,5097,410949,6671462,1783.0,2007-05-04,"13,9","10,7",0,44,"1,7",...,42,"12,5",3.0,28.0,57.0,46.0,3.0,2.0,60.170323,13.395103
11911580,4887,691880,7171716,2481.0,2019-05-10,"14,5",9,0,"33,1","3,9",...,"10,5","2,4",2.0,82.0,71.0,77.0,1.0,4.0,64.615832,19.013548
14881969,6111,817513,7158587,2482.0,2014-06-04,"12,6",11,0,"83,9","2,3",...,19,"2,5",2.0,58.0,57.0,58.0,3.0,2.0,64.404403,21.596002
4949232,2062,387777,6764419,2023.0,2018-09-03,"17,6",12,0,"54,6","3,657543",...,"25,7","8,8",3.0,71.0,38.0,71.0,2.0,-1.0,60.998689,12.924940
8142312,3345,719970,7424276,2510.0,2013-03-14,-8,-19,"0,4","50,5","1,4",...,0,0,1.0,0.0,0.0,0.0,0.0,1.0,66.856721,20.019842
5640849,2342,849616,7301804,2580.0,2012-05-03,0,NaN,0,NaN,"5,6",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.647331,22.613104
753402,315,355450,6226575,1284.0,2018-08-11,"21,5",18,"7,2","45,8","6,762877",...,49,"6,6",2.0,76.0,11.0,72.0,2.0,-1.0,56.162230,12.672296
928463,394,767839,7213871,2482.0,2020-07-24,"13,9",12,"1,5","70,6","3,1",...,"14,5","0,1",1.0,84.0,55.0,86.0,1.0,-1.0,64.940700,20.673160
2319844,967,894469,7356281,2583.0,2018-02-15,"-1,2",-1,"0,7",83,"4,917935",...,0,0,-1.0,100.0,82.0,100.0,1.0,1.0,66.078898,23.741075
16443222,6780,742576,7391452,2510.0,2018-01-28,"-10,5",-11,0,"84,3","0,783273",...,0,0,1.0,98.0,86.0,100.0,1.0,1.0,66.546473,20.467462
17070056,7018,605219,7433514,2510.0,2015-08-25,"20,1",13,0,"44,9","1,9",...,"34,7","11,9",3.0,47.0,69.0,61.0,2.0,2.0,67.000838,17.413724
7547863,3090,753223,7267488,2581.0,2018-05-30,"16,7",12,0,"35,6","4,995204",...,"49,4","26,5",5.0,17.0,66.0,52.0,3.0,4.0,65.431062,20.463355