In [6]:
import pandas as pd
import numpy as np
from datetime import datetime, date
from sweref99 import projections

In [7]:
path='./data/Brandriskdata 2000-2020.csv'
#'PunktID': str, 'E': str, 'N': str,
types={ 'PunktID': str}

In [8]:
#Reading csv file from path with dtypes
df = pd.read_csv(path, sep=';', dtype=types, )

In [9]:
#Number of rows in fire riskdataset
df.shape[0]

19188859

In [4]:
#tm is used for the conversions of easting and northing to longitude and latitude
tm = projections.make_transverse_mercator("SWEREF_99_TM")

In [5]:
#For now sample is only 50 values
sample = df.head(10)
sample[['E','N']] = df[['E','N']].fillna(0)
sample['N'] = sample['N'].astype(int)
sample['E'] = sample['E'].astype(int)
sample.head(10)

,PunktID,E,N,Kommun,Datum,Temp,Tmedel,Nederbord,RH,Vindhastighet,...,DC,ISI,BUI,FWI,FWI_index,HBV_o,HBV_u,HBV,HBV_index,Gras
7732768,3169,622491,6995342,2282.0,2013-06-08,"15,6",13,"2,6",38,"2,9",...,"139,3","1,3","33,8","2,8",2.0,56.0,54.0,65.0,2.0,2.0
5500156,2288,758768,7492962,2523.0,2011-03-03,"-1,5",0,0,"57,5","8,7",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2416893,1004,709601,6578167,120.0,2006-06-05,"13,9","11,4","0,4",54,9,...,"158,6","9,3","24,4","14,7",3.0,56.0,51.0,54.0,3.0,NaN
17359444,7137,440695,7079020,2309.0,2015-10-04,"6,8",4,"0,1","64,1","6,8",...,"65,4",1,"1,1","0,3",1.0,98.0,87.0,100.0,1.0,2.0
18459521,7590,358100,6476782,1487.0,2001-04-06,"7,6","5,3","3,8",79,"1,7",...,"12,1","0,1","2,6",0,1.0,81.0,88.0,95.0,1.0,NaN
1723795,722,499087,6864256,2361.0,2007-07-05,"21,5","17,4","0,3",57,"4,2",...,"298,6","3,4","44,2",9,3.0,56.0,38.0,48.0,3.0,NaN
6220052,2561,642134,7347013,2506.0,2008-05-17,"2,4","0,4","0,1",41,"1,5",...,0,0,0,0,1.0,96.0,97.0,100.0,1.0,1.0
3045147,1272,479880,7327307,2421.0,2019-05-12,"0,7",0,"8,8","90,8",10,...,0,0,0,0,-1.0,100.0,100.0,100.0,1.0,1.0
9816488,4039,560931,6504816,581.0,2007-06-26,"21,4","16,6",0,49,"4,3",...,"191,8","5,7","23,6","9,7",3.0,66.0,42.0,57.0,3.0,NaN
5632202,2340,376209,6218437,1260.0,2016-07-31,"20,8",16,"0,4","51,6","3,26324",...,"224,3","1,3","35,7","2,9",2.0,53.0,44.0,59.0,3.0,2.0

In [6]:
#Function that calculates number of missing data in column of dataframe and prints result.
def missing(df,column):
       x = len(df)
       if df[column].isnull().any():
           print('{0} has total of {1} null values'.format(column, df[column].isnull().sum()))
           print ('In the column {0}'.format(column), round(df[column].count()-1/x * 100, 3), '% of the cells have missing values')

In [7]:
#Missing values of column 'Gras'
missing(sample,'Gras')
missing(sample,'Vindriktning')
sample.isnull().sum(axis = 0)

Gras has total of 21 null values
In the column Gras 27.0 % of the cells have missing values
Vindriktning has total of 41 null values
In the column Vindriktning 7.0 % of the cells have missing values

PunktID           0
E                 0
N                 0
Kommun            0
Datum             0
Temp              0
Tmedel            0
Nederbord         0
RH                0
Vindhastighet     0
Vindriktning     41
FFMC              2
DMC               2
DC                2
ISI               2
BUI               2
FWI               2
FWI_index         2
HBV_o             2
HBV_u             2
HBV               2
HBV_index         2
Gras             21
dtype: int64

In [8]:
#Data info
sample.describe()


#Columns to drop from the dataframe: FFMC, DMC, DC, ISI, BUI, Gras, Vindhastighet

,E,N,Kommun,FWI_index,HBV_o,HBV_u,HBV,HBV_index,Gras
count,50.000000,5.000000e+01,50.000000,48.000000,48.000000,48.000000,48.000000,48.000000,29.000000
mean,542643.200000,6.793925e+06,1771.940000,1.770833,68.750000,63.604167,73.375000,1.875000,1.689655
std,150584.882608,3.952486e+05,716.307522,1.308557,21.800351,20.540297,20.399859,1.023656,1.198316
min,281328.000000,6.206228e+06,120.000000,-1.000000,28.000000,31.000000,37.000000,1.000000,-1.000000
25%,429931.750000,6.505194e+06,1437.750000,1.000000,49.750000,45.000000,56.750000,1.000000,1.000000
50%,499391.500000,6.680458e+06,1957.000000,2.000000,69.000000,59.500000,73.500000,1.500000,2.000000
75%,684115.250000,7.160384e+06,2403.000000,3.000000,85.250000,81.000000,91.000000,3.000000,2.000000
max,837151.000000,7.541826e+06,2584.000000,5.000000,100.000000,100.000000,100.000000,4.000000,4.000000

In [9]:
#Functions for converting easting and northing to latitudes and longitudes.
def toLat(E,N):
    lat, lon = tm.grid_to_geodetic(N,E)
    return lat
def toLon(E,N):
    lat, lon = tm.grid_to_geodetic(N,E)
    return lon

In [10]:
#Applying functions to create to new columns, Longitude and Latitude for all measuring occurances in dataframe.
sample['Latitude'] = sample.apply(lambda row: toLat(row['E'],row['N']),axis=1)
sample['Longitude'] = sample.apply(lambda row: toLon(row['E'],row['N']),axis=1)
sample

,PunktID,E,N,Kommun,Datum,Temp,Tmedel,Nederbord,RH,Vindhastighet,...,BUI,FWI,FWI_index,HBV_o,HBV_u,HBV,HBV_index,Gras,Latitude,Longitude
7732768,3169,622491,6995342,2282.0,2013-06-08,"15,6",13,"2,6",38,"2,9",...,"33,8","2,8",2.0,56.0,54.0,65.0,2.0,2.0,63.066794,17.424225
5500156,2288,758768,7492962,2523.0,2011-03-03,"-1,5",0,0,"57,5","8,7",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,67.439059,21.051839
2416893,1004,709601,6578167,120.0,2006-06-05,"13,9","11,4","0,4",54,9,...,"24,4","14,7",3.0,56.0,51.0,54.0,3.0,NaN,59.290284,18.680487
17359444,7137,440695,7079020,2309.0,2015-10-04,"6,8",4,"0,1","64,1","6,8",...,"1,1","0,3",1.0,98.0,87.0,100.0,1.0,2.0,63.833493,13.794633
18459521,7590,358100,6476782,1487.0,2001-04-06,"7,6","5,3","3,8",79,"1,7",...,"2,6",0,1.0,81.0,88.0,95.0,1.0,NaN,58.408755,12.571296
1723795,722,499087,6864256,2361.0,2007-07-05,"21,5","17,4","0,3",57,"4,2",...,"44,2",9,3.0,56.0,38.0,48.0,3.0,NaN,61.910913,14.982620
6220052,2561,642134,7347013,2506.0,2008-05-17,"2,4","0,4","0,1",41,"1,5",...,0,0,1.0,96.0,97.0,100.0,1.0,1.0,66.210979,18.158820
3045147,1272,479880,7327307,2421.0,2019-05-12,"0,7",0,"8,8","90,8",10,...,0,0,-1.0,100.0,100.0,100.0,1.0,1.0,66.065722,14.555550
9816488,4039,560931,6504816,581.0,2007-06-26,"21,4","16,6",0,49,"4,3",...,"23,6","9,7",3.0,66.0,42.0,57.0,3.0,NaN,58.679263,16.050821
5632202,2340,376209,6218437,1260.0,2016-07-31,"20,8",16,"0,4","51,6","3,26324",...,"35,7","2,9",2.0,53.0,44.0,59.0,3.0,2.0,56.094997,13.010112
7929991,3255,837151,7330602,2580.0,2016-03-30,2,1,0,"85,4","2,767015",...,0,0,1.0,100.0,91.0,100.0,1.0,1.0,65.916823,22.418172
755721,316,281328,6494986,1435.0,2007-08-14,"18,6","17,6","0,4",64,"5,6",...,"16,4","4,6",2.0,66.0,51.0,60.0,2.0,NaN,58.540303,11.242569
12606321,5201,606176,6558858,482.0,2004-06-05,"18,8","14,6",0,51,"3,8",...,"81,1","24,1",5.0,36.0,38.0,37.0,4.0,NaN,59.155622,16.856610
18885603,7789,716345,7234000,2417.0,2007-05-26,"12,3","8,9","5,3",35,"1,5",...,"11,4","0,4",1.0,74.0,86.0,91.0,1.0,3.0,65.158163,19.618336
594173,235,816141,7458574,2521.0,2002-08-22,"24,1","18,6",0,59,"1,7",...,"57,6","11,8",3.0,39.0,35.0,37.0,4.0,NaN,67.077540,22.287417
12777496,5264,775715,7294640,2560.0,2020-01-16,"-9,6",-8,"0,6","87,6",0,...,"1,6","0,2",-1.0,100.0,79.0,100.0,1.0,1.0,65.655109,21.001229
7751927,3175,409351,6576323,1780.0,2012-05-21,"23,1",17,0,"50,4","2,1",...,"23,3","7,6",3.0,48.0,54.0,51.0,3.0,2.0,59.315998,13.407474
8414173,3458,802814,7212212,2482.0,2015-09-16,"14,5",13,2,"91,2","6,4",...,"45,5",4,2.0,47.0,37.0,52.0,3.0,2.0,64.895992,21.405137
527317,194,465652,6506327,1446.0,2007-08-24,"24,2","18,9",0,53,"1,3",...,"24,6","6,6",2.0,54.0,51.0,53.0,3.0,NaN,58.695757,14.407362
16558078,6839,503987,6694714,2085.0,2019-11-08,"-1,8",-3,"5,4","96,7","1,9",...,"1,2",0,-1.0,94.0,86.0,100.0,1.0,-1.0,60.388796,15.072331
17491752,7186,426344,7012781,2321.0,2009-08-09,"19,6","18,5","0,4",64,"2,9",...,"38,2",11,3.0,37.0,45.0,42.0,4.0,NaN,63.236498,13.533891
5137979,2145,343632,6470499,1487.0,2015-09-20,"14,7",12,"0,6","61,3","2,7",...,"7,5","1,2",2.0,85.0,64.0,89.0,1.0,2.0,58.347457,12.328231
12449332,5126,347392,6540839,1460.0,2017-09-03,"16,5",12,0,"50,6","2,357075",...,"18,5","4,6",2.0,70.0,45.0,71.0,2.0,2.0,58.979846,12.344851
5317631,2208,737469,7105972,2460.0,2017-05-29,"12,6",9,0,"43,1","1,422225",...,26,"1,4",2.0,53.0,73.0,66.0,2.0,4.0,63.999113,19.858442
18207134,7482,448147,6309822,781.0,2013-04-26,"9,4",7,"5,2","58,5","3,4",...,8,"0,3",1.0,74.0,84.0,90.0,1.0,3.0,56.929147,14.148029
14741255,6061,704114,7202855,2417.0,2013-04-03,"3,3",-3,0,"58,9","4,2",...,0,0,1.0,100.0,94.0,100.0,1.0,1.0,64.887300,19.312879
5496338,2286,568272,6310517,881.0,2015-08-28,"20,4",17,"1,6","42,2","5,3",...,"98,6","18,5",4.0,34.0,31.0,42.0,4.0,2.0,56.933260,16.121880
10568866,4324,383644,6359061,1465.0,2001-07-20,22,17,4,52,"2,7",...,"8,7","0,5",1.0,82.0,63.0,85.0,1.0,NaN,57.359518,13.065766
7201893,2942,467204,6601452,1760.0,2013-08-21,"19,2",14,0,"55,2","3,6",...,18,"6,9",2.0,68.0,53.0,62.0,2.0,2.0,59.550103,14.419876
4748503,1977,492147,7178521,2313.0,2009-08-23,"11,4","10,5","1,1",68,"4,3",...,3,"0,1",1.0,86.0,73.0,91.0,1.0,NaN,64.731316,14.835124
18547815,7627,371401,6327975,1382.0,2007-03-28,"16,3","6,1",0,33,"2,2",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,57.077170,12.878479
6262484,2577,669938,6629601,330.0,2005-04-22,"5,8","2,5",0,40,"2,4",...,"31,8","8,9",3.0,48.0,71.0,63.0,2.0,NaN,59.769325,18.026358
12173441,4997,451643,6835048,2361.0,2020-04-13,"-1,1",-2,0,"48,2","10,7",...,0,0,-1.0,99.0,97.0,100.0,1.0,1.0,61.645675,14.087316
10059627,4126,508705,6585146,1880.0,2012-08-31,"14,8",14,"4,3","90,8","3,3",...,2,0,1.0,86.0,57.0,89.0,1.0,2.0,59.404870,15.153321
18435278,7576,407342,6206228,1267.0,2000-09-08,"14,2","13,8",0,92,"4,8",...,"8,4","0,9",1.0,83.0,60.0,76.0,1.0,NaN,55.992387,13.514560
8860821,3649,775069,7534522,2584.0,2007-04-28,2,"-0,5",0,45,"3,9",...,0,0,1.0,99.0,99.0,100.0,1.0,1.0,67.794781,21.532240
17072230,7019,688841,6586295,187.0,2002-04-09,"8,6","2,2",0,31,"1,4",...,"18,6","6,4",2.0,49.0,75.0,67.0,2.0,NaN,59.372934,18.323817
6503753,2665,373559,6698164,1737.0,2011-05-01,"8,5",5,0,70,"2,6",...,"40,6","9,6",3.0,28.0,74.0,61.0,2.0,3.0,60.400019,12.705054
4196236,1747,695364,7541826,2584.0,2013-04-25,3,2,0,"48,6","3,8",...,0,0,1.0,100.0,91.0,100.0,1.0,1.0,67.924580,19.661778
5038599,2098,499696,6349398,685.0,2003-04-01,"6,6","1,4",0,54,"6,5",...,"22,9","13,5",3.0,43.0,74.0,65.0,2.0,NaN,57.287573,14.994957
4704648,1963,783448,7435381,2523.0,2008-06-02,"14,4","12,2","3,5",49,"4,7",...,"22,3","2,4",2.0,59.0,80.0,83.0,1.0,3.0,66.903351,21.484637
2958890,1238,478618,6812443,2034.0,2001-08-13,"13,8","12,2","1,8",71,"0,6",...,"1,7",0,1.0,85.0,69.0,90.0,1.0,NaN,61.445199,14.599040
17023842,7000,379562,6348699,1465.0,2002-05-21,"20,5","12,7",0,27,"2,8",...,46,"18,9",4.0,40.0,51.0,46.0,3.0,NaN,57.265432,13.003007
13537612,5578,447546,6824687,2039.0,2007-08-08,"19,3","16,3","6,9",66,"2,8",...,"15,4","0,5",1.0,75.0,49.0,76.0,1.0,NaN,61.552140,14.012966
18810193,7751,547348,6713583,2080.0,2011-07-24,"16,1",17,"10,5","83,2","5,3",...,7,0,1.0,82.0,45.0,83.0,1.0,NaN,60.555444,15.863400
1491120,621,468906,6301675,764.0,2014-07-08,"27,2",22,"0,1",62,"5,4",...,"44,7",19,4.0,46.0,37.0,52.0,3.0,0.0,56.857819,14.490087
7669662,3144,576575,6666203,2084.0,2009-07-30,"20,4","15,4",0,63,"2,6",...,16,"4,2",2.0,62.0,59.0,61.0,2.0,NaN,60.125647,16.378157
12491410,5146,415331,6621851,1763.0,2011-06-08,"21,6",19,"0,8","73,9","2,8",...,"37,8","4,1",2.0,50.0,43.0,56.0,3.0,2.0,59.725938,13.494377
1804808,750,564001,6695075,2083.0,2000-06-29,"15,1","12,7","2,1",71,"4,3",...,"5,6","0,3",1.0,79.0,46.0,79.0,1.0,NaN,60.386995,16.161057
8970336,3699,448346,6644774,1782.0,2019-07-16,"13,4",12,"0,4","75,4","5,6",...,"17,7","1,3",2.0,78.0,42.0,78.0,1.0,-1.0,59.937165,14.075663